syncfusion-content/javascript-docs

js/Electron.md
js/PdfViewer/Appearance.md

Worked on site audit issues, merge these changes.
Regards,
Gowthaman

SEO-2344_Site_Audit_Issues

---

js-toc.html
js/installation/mac-installer/how-to-download.md
js/installation/mac-installer/how-to-install.md
js/installation/offline-installer/how-to-download.md
js/installation/web-installer/how-to-download.md

IN-18200-UG-Documentation-Javascript-hotfix

---

js/installation/Installation-Errors.md
js/installation/mac-installer/how-to-download.md
js/installation/offline-installer/how-to-download.md
js/installation/web-installer/how-to-download.md

IN-18200-UG-D0cumentation-Javascript-hotfix

---

js/Maps/Public-Methods-and-Events.md
js/WebAPI/DocIO.md

Worked on site audit issues, merge these changes,
Regards,
Gowthaman

SEO-2370_Site_Audit_Issues

---

js/Grid/Filter.md
js/Schedule/getting-started.md

Worked on Site Audit issues, so merge these changes,
Regards,
Gowthaman

SEO-2423_Site_Audit_Issues

---

js/DateTimePicker/Display-format.md
js/DropDownList/Checkbox.md
js/ReportViewer/how-to/create-report.md

Worked on Dropping Keywords changes, so merge these changes,
Regards,
Gowthaman

SEO-2472_Dropping_Keywords

---

js/DropDownList/DataBinding.md
js/Grid/Style-and-Appearance.md
js/Schedule/keyboard-navigation.md

Worked on site audit issues, so merge these changes,
Regards,
Gowthaman

SEO-2475_Site_Audit_Issues

---

js/TypeScript.md

Images not loaded issue in EJ1 documentation has been resolved.

(JS-64311):correction added

---

js/Chart/Getting-Started.md
js/Diagram/Connector.md
js/Diagram/Node.md
js/SpellCheck/Functionalities.md

Hi @ChristoIssac,
|Task Category| Pages With Redirect - Search console|
|:--|:--|
|Issue count| Help site links - 1000 |
|Fixed Count| Help site links - 5 |
|Analysis| Inspecting the links and found referring pages |
|Solution| replaced the exact URL instead of old URL |
|Hotfix PR| https://github.com/syncfusion-content/javascript-docs/pull/227 | 
|Task link|https://syncfusion.atlassian.net/browse/SEO-2684|
|Excel| N/A |
Regards,
Gowthaman

SEO-2684-Coverage-Page-With-Redirect-UG

---

js/Diagram/Interaction.md

Hi @ChristoIssac,
|Task Category| Pages With Redirect - Search console|
|:--|:--|
|Issue count| Help site links - 1000 |
|Fixed Count| Help site links - 2 |
|Analysis| Inspecting the links and found referring pages |
|Solution| replaced the exact URL instead of old URL |
|Hotfix PR| https://github.com/syncfusion-content/javascript-docs/pull/235 | 
|Task link|https://syncfusion.atlassian.net/browse/SEO-2684|
|Excel| N/A |
Regards,
Gowthaman

SEO-2684-Coverage-report-pages-with-redirect

---

js/ComboBox/DataBinding.md

|Title|Description|
|:--|:--|
|**Task Category** | Need to rename 2 image - Alt Text|
|**Content task link/ Mail screenshot** | N/A |
|**Hotfix PR link** | https://github.com/syncfusion-content/javascript-docs/pull/190
|**Ticket link/Task link** | https://syncfusion.atlassian.net/browse/SEO-2705 |
|**Excel/SharePoint link** | N/A |

SEO-2488 - JavaScript Combobox image alt text changes

---

js/Chart/Getting-Started.md
js/Diagram/Port.md

Hi Aishwarya,
Worked on page with redirect for help links, so merge these changes
Regards,
Gowthaman

SEO-3146-coverage-page-with-redirect-help

---

js/Overview.md

Please review http to https link issues changes.
Regards,
Sharly A.

SEO-3108 - JavaScript http to https

---

js/DataManager/Helper-Functions.md
js/DatePicker/Behavior-Settings.md
js/Diagram/Automatic-Layout.md
js/Schedule/customization.md

Please review the changes for Page with redirect in JS.
Regards,
Yvone.

SEO-3239 JS Page with redirect

---

js/Chart/Chart-Title.md
js/Control-Initialization.md
js/Diagram/Constraints.md
js/TypeScript.md

Please review page with redirect changes in JS controls.
Regards,
Sharly A.

SEO-3222 - JavaScript Controls page with redirect

---

js/Overview.md

please review the changes for JS overview.
Regards,
Sharly A.

SEO-3267 - JS overview http to https

---

js/DateRangePicker/display-format.md
js/DateTimePicker/Overview.md
js/Grid/Overview.md
js/ReportDesigner/Compose-Report/Configure-ReportItem/Line-ReportItem.md

Please review the changes for JS Desc too long short.
Regards,
Yvone.

SEO-3147 JS Desc too long short

---

js/Button/Overview.md
js/Chart/Exporting.md
js/DateRangePicker/behavior-settings.md
js/Grid/Globalizationandlocalization.md
js/Maps/Getting-Started.md
js/SunburstChart/Legend.md

Worked on bing report issues, so merge these changes
Regards,
Gowthaman

SEO-3261-bing-report-issues

---

js/Overview.md

Please review the changes for JS Overview permanent redirect.
Regards,
Sharly A.

SEO-3226 - JS Overview changes

---

js/DataManager/Sorting.md
js/ListView/VirtualScrolling.md
js/Listbox/Grouping.md
js/PivotGrid/OLAP-Connectivity.md
js/TreeView/Drag-and-Drop.md

Have changed title, description, H1 and named images.
Regards,
Yvone.

SEO-3569 JavaScript Site Audit

---

js/Grid/Data-Binding.md

Have changed redirect links.
Regards,
Yvone.

SEO-3460 JavaScript Redirect

---

js/DataManager/ServerTimezoneOffset.md
js/DropDownTree/databinding.md
js/Gantt/Columns.md
js/Gantt/Critical-feature.md

Worked on Bing report issues, so merge these changes
Regards,
Gowthaman

SEO-3615-bing-issues

---

js/Chart/Data-Markers.md
js/Grid/Enable-Persistence.md

Hello, 
Worked on the links with redirects,
Regards,
Beryl

SEO-171356-Links-With-Redirects-JS

---

js/Chart/Chart-Title.md
js/Grid/Getting-Started.md

Hello,
I have worked on the links with redirects.
Regards,
Beryl.

SEO-171719-Links-With-Redirects

---

js/Maps/Layers.md
js/TreeGrid/Searching.md

Have changed title, description, image alt and h1.
Regards,
Yvone.

SEO-171762 JavaScript Bing report

---

js/Chart/Exporting.md
js/Schedule/getting-started.md

Have changed page with redirect links.
Regards,
Yvone.

SEO-171761 JavaScript Redirect links

---

js/DataManager/Table-Model.md
js/ListView/Data-Binding.md

Hi @gowthamanthavasiyappan ,
Have changed title, H1 and description for JavaScript.
Regards,
Yvone.

SEO-172157 JavaScript Desc too long short

---

js/Overview.md

Please review JS Overview changes.
Regards,
Sharly A.

SEO-172146 - JS Overview Permanent redirect link

---

js/Checkbox/Easy-customization.md
js/CircularGauge/Legend.md
js/ComboBox/Getting-Started.md
js/ComboBox/howto.md
js/Currency/Keyboard-Interaction.md
js/DataManager/Data-Binding.md
js/DataManager/Table-Model.md
js/DataManager/how-to.md
js/DatePicker/Getting-Started.md
js/DatePicker/How-To.md
js/DatePicker/Validation.md
js/Dialog/Getting-Started.md
js/DragandDrop/Getting-Started.md
js/DropDownList/Accessibility.md
js/DropDownList/Customization.md
js/DropDownList/DataBinding.md
js/DropDownList/Functionalities.md
js/DropDownList/Getting-Started.md
js/DropDownList/HowTo.md
js/DropDownList/Rendering-Mode.md
js/DropDownTree/Functionalities.md
js/DropDownTree/Getting-Started.md
js/DropDownTree/LoadOnDemand.md
js/DropDownTree/Localization.md
js/DropDownTree/databinding.md

Hi @Girija-Rajendran,
Worked on redirection-related fixes, so merge these changes,
Regards,
Gowthaman

SEO-172685-JavaScript-redirection-tool-fixes-1

---

js/Accessibility.md
js/CDN.md
js/Compatibility-and-System-Requirements.md
js/Configuration-and-Deployment.md
js/Custom-script-generator.md
js/Electron.md
js/KnockoutJS.md
js/NuGet-Packages.md
js/Overview.md
js/Persistence.md
js/System-Requirements.md
js/Theme-Studio.md
js/TypeScript.md
js/Unobtrusive-Support.md
js/bootstraptheme.md
js/compatibility-ej1-ej2.md
js/format.md
js/ionic.md
js/ionic3.md
js/requirejs.md
js/validation.md

Hi @Girija-Rajendran,
Worked on redirection-related fixes, so merge these changes,
Regards,
Gowthaman

SEO-172685-JavaScript-redirection-tool-fixes-2

---

js/FileExplorer/Context-Menu.md
js/FileExplorer/Getting-Started.md
js/FileExplorer/How-To.md
js/FileExplorer/Overview.md
js/FileExplorer/Toolbar.md
js/Gantt/Baseline.md
js/Gantt/Columns.md
js/Gantt/Context-Menu.md
js/Gantt/Critical-feature.md
js/Gantt/Customizations.md
js/Gantt/Data-Binding.md
js/Gantt/Duration-units.md
js/Gantt/Exporting.md
js/Gantt/HistogramView.md
js/Gantt/Rows.md
js/Gantt/Timescale-Modes.md
js/Gantt/Toolbar.md
js/Gantt/WorkBreakdownStructure.md
js/Gantt/Working-time-range.md
js/Grid/Cell.md
js/Grid/Columns.md
js/Grid/Data-Binding.md
js/Grid/Editing.md
js/Grid/Exporting.md
js/Grid/Getting-Started.md
js/Grid/Grouping.md
js/Grid/How-to.md
js/Grid/Print-Grid.md

Hi @Girija-Rajendran,
Worked on redirection-related fixes, so merge these changes,
Regards,
Gowthaman

SEO-172685-JavaScript-redirection-tool-fixes-3

---

js/ListView/Data-Binding.md

Hi @MallikaRK,
Worked on description too long / short.
Regards,
Sharly A.

SEO-172159 - Description too long / short

---

js/TreeGrid/Searching.md

Hi. Girija-Rajendran,
Kindly review.
Modifying the missing H1 in the PR below.
Regard,
Dickson J.

SEO-172168-js-TreeGrid- control-missing- H1

---

js/Overview.md

Hello,
I have worked on the links with redirects.
Regards,
Beryl.

SEO-172101-Links-With-Redirects-JS-Overview

---

js/Grid/How-to.md

Have changed JavaScript Page with Redirect.
Regards,
Yvone.

SEO-174775 JavaScript Page with Redirect

---

js/Button/Repeat-Button.md
js/FileExplorer/Toolbar.md
js/Gantt/Appearance-and-Styling.md
js/Slider/Updating-slider-value.md
js/TreeGrid/Filtering.md
js/TreeGrid/Rows.md
js/TreeGrid/Selection.md
js/TreeGrid/Sorting.md

Hi @MallikaRK ,
I have made changes in the description section, please review.
Regards,
Scholar.

SEO-174730 JavaScript Description too long

---

js/Dialog/Getting-Started.md
js/Ribbon/Getting-Started.md
js/Schedule/getting-started.md

Have changed Page with Redirect links.
Regards,
Yvone.

SEO-175190 JavaScript Page with Redirect

---

js/Schedule/getting-started.md

Corrected the script and style tag in the EJ1 Schedule UG documentation

documentation(ES-843999): Corrected the script and style tag in the EJ1 Schedule UG documentation

---

js/installation/web-installer/how-to-download.md

Have changed Page with Redirect.
Regards,
Yvone.

SEO-175659 JS Page with Redirect

---

js/TreeView/Getting-Started.md

Please review changes for JavaScript redirect links.
Regards,
Selline Rita.

SEO-175689-JavaScript-Redirect

---

js/Chart/Exporting.md
js/TreeGrid/Columns.md
js/Upgrade/how-to-upgrade.md

Hi @MallikaRK ,
Have made changes on the redirect links. Please review.
Thanks.
Regards,
Edith.

SEO-175680-JS-UG-page-with-redirects-links

---

js/Grid/Summary.md

Hello,
Worked on the links with redirects.
Regards,
Beryl.

SEO-175653-JS-Pages-With-Redirects

---

js/SplitButton/Easy-customization.md
js/TreeGrid/Context-Menu.md

Hello,
I have worked on the multiple H1
Regards,
Beryl.

SEO-176113-JS-Multiple-H1

---

js/Chart/3D-Chart.md
js/DropDownTree/Checkbox.md
js/Grid/Paging.md
js/GroupButton/Overview.md
js/MediaPlayer/Getting-Started.md
js/Menu/Data-binding.md
js/Toolbar/Data-binding.md

Hello,
I have worked on the image alt text.
Regards,
Beryl.

SEO-176113-Image-Alt-Text-JS

---

js/Chart/Chart-Series.md
js/Gantt/How-to/Change-Splitter-position.md

HI @MallikaRK ,
Please review the changes.
Thanks.
Regards,
Edith.

SEO-176496-js-page-with-redirect-links

---

js/Autocomplete/Getting-Started.md
js/DropDownList/Getting-Started.md

Hello,
I have worked on the links with redirects.
Regards,
Beryl.

SEO-177279-Page-With-Redirect-JS

---

js/RadialMenu/getting-started.md
js/installation/web-installer/how-to-download.md

Hi @MallikaRK
Kindly review my PR in page with redirect UG help under JavaScript.
Regards.
Dickson J

SEO-174654-JavaScript-Page-With-Redirect-UG-Help

---

js/PdfViewer/Getting-Started.md
js/PdfViewer/Localization.md
js/PdfViewer/Toolbar-Customization.md
js/Spreadsheet/Open-and-Save.md

Hi @MallikaRK,
I have fixed the http issues, please review.
Regards,
Scholar.

SEO-181471-JavaScript-HTTP-TO-HTTPS

---

js/WebAPI/DocumentEditor.md

Have worked on Missing H1, please review.
Regards,
Yvone.

SEO-183463 JavaScript Missing H1

---

js/DatePicker/Behavior-Settings.md
js/Diagram/Label.md

Have modified title, H1 and description, please review.
Regards,
Yvone.

SEO-184192 JavaScript Page with Redirect

---

js/PdfViewer/Getting-Started.md

Hi @GowthamanMayil,
Please review the below PR,
Title | Description
-- | --
Task Category | Permanent Redirect|
Content Task Link/Mail Screenshot | NA|
|Hotfix |https://github.com/syncfusion-content/javascript-docs/pull/506|
Ticket/Task link |https://dev.azure.com/Syncfusion-Infrastructure/Syncfusion%20SEO/_workitems/edit/188023|
|Changes Made | Reason for change |
|-- | -- |
|Changed redirect links| To avoid redirect links |
Regards,
Yvone.

SEO-188023 JavaScript PDF Viewer Permanent Redirect
